#!/bin/sh -e
### BEGIN INIT INFO
# Provides:          pppd-dns
# Required-Start:    $local_fs
# Required-Stop:
# Default-Start:     
# Default-Stop:
# Short-Description: Restore resolv.conf if the system crashed.
### END INIT INFO
