#!/bin/sh
set -e
### BEGIN INIT INFO
# Provides:          stop-readahead-fedora
# Required-Start:    $all
# Required-Stop:     $remote_fs
# Default-Start:     
# Default-Stop:      0 1 6
# Short-Description: init script for stopping readahead profiling
### END INIT INFO
