#! /bin/sh
### BEGIN INIT INFO
# Provides: bluetooth
# Required-Start:    $local_fs $syslog $remote_fs 
# Required-Stop:     $local_fs $syslog $remote_fs
# Default-Start:     
# Default-Stop:      0 1 6
# Short-Description: Start bluetooth daemons
### END INIT INFO
