#! /bin/sh

### BEGIN INIT INFO
# Provides:          bootchart2
# Required-Start:    $remote_fs $all
# Required-Stop:
# Default-Start:     
# Default-Stop:
# Short-Description: Stop bootchartd
# Description:       This script stops the bootchartd daemon after the
#                    system booted.
### END INIT INFO
