#!/bin/sh
### BEGIN INIT INFO
# Provides:          dbus
# Required-Start:    sysfs proc 
# Required-Stop:     $remote_fs $syslog
# Default-Start:     S 2 3 4 5
# Default-Stop:
# Short-Description: D-Bus systemwide message bus
# Description:       D-Bus is a simple interprocess messaging system, used
#                    for sending messages between applications.
### END INIT INFO

