#!/bin/sh
### BEGIN INIT INFO
# Provides:          dbus
# Required-Start:    $syslog
# Required-Stop:     $syslog
# Default-Start:     
# Default-Stop:
# Short-Description: D-Bus systemwide message bus
# Description:       D-Bus is a simple interprocess messaging system, used
#                    for sending messages between applications.
### END INIT INFO
