#!/bin/sh

### BEGIN INIT INFO
# Provides:          hdparm
# Required-Start:    procfs
# Required-Stop:
# Should-Start:      udev
# Default-Start:     S
# Default-Stop:
# Short-Description: Tune IDE hard disks
### END INIT INFO
