#!/bin/sh
### BEGIN INIT INFO
# Provides:          kbd
# Required-Start:    $remote_fs
# Required-Stop:
# Default-Start:     
# Default-Stop:
# X-Interactive:     true
# Description: Set console screen modes and fonts
# Short-Description:    Prepare console
### END INIT INFO
