#!/bin/sh
set -e
### BEGIN INIT INFO
# Provides:          later-readahead
# Required-Start:    $remote_fs
# Required-Stop:
# Should-Start:      mountkernfs
# X-Start-Before:
# Default-Start:     
# Default-Stop:
# Short-Description: init script for readahead-fedora
### END INIT INFO
