#!/bin/sh
### BEGIN INIT INFO
# Provides:          motd
# Required-Start:    $local_fs
# Required-Start:    init $local_fs
# Required-Stop:
# Should-Start:
# Default-Start:     1 2 3 4 5
# Default-Stop:
# Short-Description: Create dynamic part of /etc/motd
# Description:       /etc/motd is user-editable and static.  This script
### END INIT INFO
