#! /bin/sh
### BEGIN INIT INFO
# Provides:          network-manager
# Required-Start:    $remote_fs dbus udev
# Required-Stop:     dbus udev
# Should-Start:	     $syslog
# Should-Stop:       $syslog
# Default-Start:     
# Default-Stop:      0 1 6
# Short-Description: network connection manager
# Description:       Daemon for automatically switching network 
#		     connections to the best available connection.
### END INIT INFO
