#!/bin/sh
### BEGIN INIT INFO
# Provides:       nodm
# Should-Start:   console-screen kbd hal bluetooth
# Required-Start: $remote_fs
# Required-Stop:
# Default-Start:  
# Default-Stop:   0 1 6
# Short-Description: No Display Manager
### END INIT INFO
