#!/bin/sh

### BEGIN INIT INFO
# Provides:        ntp
# Required-Start:  $network $remote_fs $syslog
# Required-Stop:   $network $remote_fs $syslog
# Default-Start:   
# Default-Stop: 
# Short-Description: Start NTP daemon
### END INIT INFO

