#!/bin/sh
### BEGIN INIT INFO
# Provides:          slim
# Required-Start:    $mountall udev dbus
# Required-Stop:     $mountall 
# Should-Start:      xfs $named slapd networking network-manager
# Should-Stop:       xfs $named slapd
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start/stop the SLiM daemon.
### END INIT INFO
