#! /bin/sh

### BEGIN INIT INFO
# Provides:		sshd
# Required-Start:	$all
# Required-Stop:	
# Default-Start:	1 2 3 4 5
# Default-Stop:		0 6	
# Short-Description:	OpenBSD Secure Shell server
### END INIT INFO
