#! /bin/sh

### BEGIN INIT INFO
# Provides:		sshd
# Required-Start:	$remote_fs $syslog
# Required-Stop:	$remote_fs $syslog
# Default-Start:	
# Default-Stop:		
# Short-Description:	OpenBSD Secure Shell server
### END INIT INFO
