#! /bin/sh

### BEGIN INIT INFO
# Provides:		sshd
# Required-Start:	$desktop
# Required-Stop:	$syslog
# Default-Start:	2 3 4 5
# Default-Stop:		
# Short-Description:	OpenBSD Secure Shell server
### END INIT INFO
