#!/bin/sh -e
### BEGIN INIT INFO
# Provides:          udev-finish
# Required-Start:    $local_fs
# Required-Stop:     
# Default-Start:      
# Default-Stop:
# Short-Description: Copy rules generated while the root was ro
### END INIT INFO

