#!/bin/sh -e
### BEGIN INIT INFO
# Provides:          udev-finish
# Required-Start:    udev $local_fs
# Required-Stop:     
# Default-Start:     1 2 3 4 5  
# Default-Stop:
# Short-Description: Copy rules generated while the root was ro
### END INIT INFO

