#!/bin/sh -e
### BEGIN INIT INFO
# Provides:          udev
# Required-Start:    mountkernfs 
# Required-Stop:     
# Default-Start:     1 2 3 4 5
# Default-Stop:
# Short-Description: Start udevd, populate /dev and load drivers.
### END INIT INFO
