#!/bin/sh

### BEGIN INIT INFO
# Provides:       vboxadd-service
# Required-Start: vboxadd
# Required-Stop:  vboxadd
# Default-Start:  
# Default-Stop:   0 1 6
# Description:    VirtualBox Additions Service
### END INIT INFO

