#! /bin/sh
### BEGIN INIT INFO
# Provides:          wicd
# Required-Start:    $remote_fs init
# Required-Stop:     $remote_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Starts and stops Wicd
# Description:       Starts and stops Wicd, a network manager
### END INIT INFO

