#! /bin/sh
#
# rcS
#
# Call all S??* scripts in /etc/rcS.d/ in numerical/alphabetical order
#

#/bin/mount -t proc /proc -n -o noatime,nodiratime,nodev,noexec,nosuid
#mknod kmsg c 1 11

cinit=$(grep -wo cinit /proc/cmdline)

if [ "$cinit" != "" ]; then
 /root/build/cinit 
 [ "$?" = "0" ] && exit 0
fi

exec /etc/init.d/rc S
