#! /bin/sh
#
# rcS
#
# Call all S??* scripts in /etc/rcS.d/ in numerical/alphabetical order
#

/root/build/preload &

#/bin/mount -t proc /proc -n -o noatime,nodiratime,nodev,noexec,nosuid
#mknod kmsg c 1 11

/root/cinit > /var/log/kmsg
[ "$?" = "0" ] && exit 0

exec /etc/init.d/rc S
